language: java

addons:
  sonarcloud:
    organization: "letronul-github"

script: mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.organization=letronul-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=90f1c5b52bef9299ab72800f00083bbd42da6e63 -Dsonar.projectKey=java350:master -Dsonar.branch=master